# Generated by Django 4.2.1 on 2023-05-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='PruebaModels',
        ),
    ]
