# Generated by Django 4.2.1 on 2023-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_habilidadesmodel_alter_empleadomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilidadesmodel',
            options={'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades Empelado'},
        ),
        migrations.AddField(
            model_name='empleadomodel',
            name='abilityu',
            field=models.ManyToManyField(to='empleados.habilidadesmodel'),
        ),
    ]
