# Generated by Django 4.2.1 on 2023-05-22 18:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_rename_abilityu_empleadomodel_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadomodel',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='habilidadesmodel',
            options={'ordering': ['id'], 'verbose_name': 'Habilidad', 'verbose_name_plural': 'Habilidades Empelado'},
        ),
        migrations.AddField(
            model_name='empleadomodel',
            name='cv',
            field=ckeditor.fields.RichTextField(default='Falta Compeltar'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='habilidadesmodel',
            unique_together={('ability',)},
        ),
    ]
